<?php

namespace VDM\VdmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VdmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmRepository extends EntityRepository
{
}
