<?php

namespace VDM\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
// use \DateTime;

/**
 * VdmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmRepository extends EntityRepository
{
   public function findVdmByParameters($params)
    {
      $query = $this->createQueryBuilder('myVdm');

      if($params['author'] !== null){
        $query->where('myVdm.author = :author')
              ->setParameter('author', $params['author']);
      }

      if($params['from'] !== null){
        $query->andWhere('myVdm.published >= :from')
              ->setParameter('from', $params['from']);
      }

      if($params['to'] !== null){
        $query->andWhere('myVdm.published <= :to')
              ->setParameter('to', $params['to']);
      }

      return $query->getQuery()->getResult();
    }
}
